eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080
ribbon:
  ReadTimeout: 60000

spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"

      routes:
        - id: authentication-services
          uri: lb://authentication-services:9201
          predicates:
            - Path=/authentication-services/**
          filters:
            - RewritePath=/authentication-services(?<segment>/?.*), $\{segment}

        - id: chat-service
          uri: lb://chatservice:9205
          predicates:
            - Path=/chat-service/**
          filters:
            - RewritePath=/chat-service(?<segment>/?.*), $\{segment}

        - id: feedback-service
          uri: lb://feedback-service:7003
          predicates:
            - Path=/feedback-service/**
          filters:
            - RewritePath=/feedback-service(?<segment>/?.*), $\{segment}

        - id: MailServiceApp
          uri: lb://Mail-services:9202
          predicates:
            - Path=/MailServiceApp/**
          filters:
            - RewritePath=/MailServiceApp(?<segment>/?.*), $\{segment}

        - id: Recommendation-Service
          uri: lb://recommendation-services:8082
          predicates:
            - Path=/Recommendation-Service/**
          filters:
            - RewritePath=/Recommendation-Service(?<segment>/?.*), $\{segment}


        - id: shipping-services
          uri: lb:// shipping-services:7575
          predicates:
            - Path=/shipping-services/**
          filters:
            - RewritePath=/shipping-services(?<segment>/?.*), $\{segment}

        - id: user-profile
          uri: lb://user-profile:8085
          predicates:
            - Path=/user-profile/**
          filters:
            - RewritePath=/user-profile(?<segment>/?.*), $\{segment}

        - id: vendor-service
          uri: lb://vendor-service:8083
          predicates:
            - Path=/vendor-service/**
          filters:
            - RewritePath=/vendor-service(?<segment>/?.*), $\{segment}

        - id: product-webapp
          uri: lb://product-webapp
          predicates:
            - Path=/**
          filters:
            - RewritePath=/product-webapp(?<segment>/?.*), $\{segment}
